import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar";
import Analytics from "../components/Analytics";
import WeatherDataProvider from "@/providers/WeatherDataProvider";

const font = Inter({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
    title: "Weatherrr",
    // description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <WeatherDataProvider>
                <body className={font.className}>
                    <div className="h-screen w-screen overflow-hidden flex">
                        <div className="h-full w-1/5">
                            <Sidebar />
                        </div>
                        <div className="h-full flex-1 overflow-y-auto">
                            <div className="flex h-full w-full flex-1 overflow-hidden">
                                <div className="h-full flex-1 overflow-y-auto">
                                    {children}
                                </div>
                                <Analytics />
                            </div>
                        </div>
                    </div>
                </body>
            </WeatherDataProvider>
        </html>
    );
}
